spinnaker/kayenta

kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java

This will look in older places for the execution request, which moved but older pipelines may not have been updated.  I'll remove the code sometime in the future, once I find out how to rewrite history in kayenta's data store, or the older executions are expired out.

fix(json): look in older places for execution context too

---

Dockerfile.slim
kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryConfig.java
kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java
kayenta-core/src/main/java/com/netflix/kayenta/canary/providers/QueryConfigUtils.java
kayenta-core/src/test/groovy/com/netflix/kayenta/canary/providers/QueryConfigUtilsSpec.groovy
kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/metrics/StackdriverMetricsService.java
kayenta-stackdriver/src/test/groovy/com/netflix/kayenta/providers/StackdriverCanaryMetricSetQueryConfigSpec.groovy

reset HEAD of release-1.7.x to HEAD of master.  pulls in following two fixes:
https://github.com/spinnaker/kayenta/pull/292
https://github.com/spinnaker/kayenta/pull/294

Release 1.7.x dockerfile slim and custom filter template fixes

---

kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java

cherry-pick https://github.com/spinnaker/kayenta/pull/296 into release-1.7.x branch

fix(build): Add back inadvertently-removed imports. (#296)

---

kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricSetPair.java

fix(gcs): fixes metric set pair deserialization

---

kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/WeightedSumScorer.scala
kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ScorerSuite.scala

New nodata rules:
* If 50% or more metrics in the entire canary report Nodata, the final score will be forced to 0.0.
* If all metrics inside a group report Nodata, the group is marked with a 0.0 score.
* Compute the summary score as before, except that entirely Nodata groups are considered a 100% Pass, which in effect makes its weight ignored.  That is, if we have two groups, one with just Nodata, one with a score of 100.0, the final result will be 100.0.

fix(Judge): Handle Nodata groups correctly

---

kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/RandomDummyJudge.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/stats/DescriptiveStatistics.scala

Move the `toMap` method to the `MetricStatistics` class and cleanup the RandomDummyJudge.

chore(stats): Move the toMap method to the MetricStatistics class

---

kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/WeightedSumScorer.scala
kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ScorerSuite.scala

Round the final Summary Score to 2 decimals places (Fixes #271).

fix(judge): Round the Summary Score to 2 decimal places

---

kayenta-objectstore-configbin/src/main/java/com/netflix/kayenta/configbin/storage/ConfigBinStorageService.java

This is a quick fix to retry certain ConfigBin queries which sometimes return status 500 or similar.

fix(configbin): Add retry support for queries

---

kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsService.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/canary/providers/metrics/PrometheusCanaryMetricSetQueryConfig.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/canary/PrometheusCanaryScope.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/controllers/PrometheusFetchController.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
kayenta-prometheus/src/test/groovy/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsServiceSpec.groovy

Also some preparatory work for dry-running query generation.

feat(prometheus): Move resourceType from canary scope to query config.

---

kayenta-core/src/main/java/com/netflix/kayenta/persistence/config/JedisConfig.java
kayenta-core/src/main/java/com/netflix/kayenta/persistence/config/RedisConnectionInfo.java

This is an example PR for issue
https://github.com/spinnaker/spinnaker/issues/3463

feat: Add SSL support to jedis config

---

kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/controllers/AtlasFetchController.java
kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/orca/AtlasFetchTask.java
kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsService.java
kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java
kayenta-core/src/main/java/com/netflix/kayenta/metrics/orca/MetricSetMixerServiceTask.java
kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/controller/DatadogFetchController.java
kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/orca/DatadogFetchTask.java
kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/controller/InfluxDbFetchController.java
kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/orca/InfluxDbFetchTask.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/controllers/PrometheusFetchController.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/orca/PrometheusFetchTask.java
kayenta-prometheus/src/test/groovy/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsServiceSpec.groovy
kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/orca/SignalFxFetchTask.java
kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/controllers/StackdriverFetchController.java
kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/metrics/StackdriverMetricsService.java
kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/orca/StackdriverFetchTask.java

Also pulled out some common code to handle the dryrun yes/no logic.

feat(stackdriver): Add dryRun support.

---

build.gradle

The deps as 'XXX' seems a bit troubling... How does this currently work, @duftler ?

chore(builds): Reformat spinnaker deps version

---

kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryController.java

Add ability to supply application and parentPipelineId to adhoc canary endpoint.

Add ability to supply application and parentPipelineId to adhoc canary endpoint.

---

kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MeanInequalityClassifier.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/RandomClassifier.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/evaluation/BinaryClassificationEvaluator.scala
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/WeightedSumScorer.scala

While doing some testing I discovered that I wanted the feature described in https://github.com/spinnaker/kayenta/issues/330.
This PR is an attempt at solving that request, hopefully this is something close to what you were thinking about.

Allow metrics to be specified as must have data.

---

kayenta-judge/src/main/scala/com/netflix/kayenta/judge/RemoteJudge.java
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/config/RemoteJudgeConfiguration.java
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/config/RemoteJudgeConfigurationProperties.java
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/model/RemoteJudgeRequest.java
kayenta-judge/src/main/scala/com/netflix/kayenta/judge/service/RemoteJudgeService.java
kayenta-web/config/kayenta.yml

Add a http-based remote judge.
Sample config:
```yaml
remoteJudge:
enabled: true
endpoint:
baseUrl: http://www.example.com/a/b/c/d
```

feat(RemoteJudge)

---

.travis.yml
gradle.properties

Manual cherry-pick of https://github.com/spinnaker/kayenta/pull/450 into 1.10.x branch

fix(orca): Bump orca to 6.119.0 to resolve redis evalsha issue. (#450)

---

kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryExecutionStatusResponse.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/controller/StandaloneCanaryAnalysisController.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionRequest.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionRequestScope.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionResponse.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionResult.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionStatusResponse.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryExecutionResult.java

refactor(standalone-canary-analysis): Edits to API descriptions

refactor(standalone-canary-analysis): Edits to API descriptions

---

json-formats.md
kayenta-wavefront/kayenta-wavefront.gradle
kayenta-wavefront/src/main/java/com/netflix/kayenta/canary/providers/metrics/WavefrontCanaryMetricSetQueryConfig.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/canary/WavefrontCanaryScope.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/canary/WavefrontCanaryScopeFactory.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/config/WavefrontConfiguration.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/config/WavefrontConfigurationProperties.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/config/WavefrontManagedAccount.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/controller/WavefrontFetchController.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/metrics/WavefrontMetricsService.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/orca/WavefrontFetchStage.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/orca/WavefrontFetchTask.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/security/WavefrontCredentials.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/security/WavefrontNamedAccountCredentials.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/service/WavefrontRemoteService.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/service/WavefrontTimeSeries.java
kayenta-wavefront/src/test/java/com/netflix/kayenta/wavefront/canary/WavefrontCanaryScopeFactoryTest.java
kayenta-wavefront/src/test/java/com/netflix/kayenta/wavefront/metrics/WavefrontMetricsServiceTest.java
kayenta-wavefront/src/test/java/com/netflix/kayenta/wavefront/service/WavefrontTimeSeriesTest.java
kayenta-web/config/kayenta.yml
kayenta-web/kayenta-web.gradle
kayenta-web/src/main/java/com/netflix/kayenta/Main.java
settings.gradle

Adds Wavefront as a query store for Kayenta and address the first part of https://github.com/spinnaker/kayenta/issues/314

feat(wavefront): Add Wavefront integration

---

kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java

Instead of pulling data from the judge object store, return the results directly from the stage as we have direct access to it already.

fix(results): use judge results in pipeline, not storage

---

build.gradle
gradle/init-publish.gradle
kayenta-graphite/kayenta-graphite.gradle
kayenta-signalfx/kayenta-signalfx.gradle

https://github.com/spinnaker/spinnaker/issues/3997

fix(build): make gradle use https

---

kayenta-web/kayenta-web.gradle

Prereq for spinnaker/kork#273 merge

chore(dependencies): ensure direct dependency on kork-secrets-aws

---

build.gradle
gradle.properties
kayenta-bom/kayenta-bom.gradle
kayenta-core/kayenta-core.gradle
kayenta-graphite/kayenta-graphite.gradle
kayenta-orca/kayenta-orca.gradle
kayenta-signalfx/kayenta-signalfx.gradle
settings.gradle

This makes downstream dependencies easier.
NOTE: Exposing `orca-bom` which then brings in `kork-bom`

feat(kayenta-bom): publish kayenta-bom

---

kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionRequest.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/orca/stage/SetupAndExecuteCanariesStage.java

chore: Made some tweaks to the /standalone_canary_analysis api docs.

chore: Made some tweaks to the /standalone_canary_analysis api docs.

---

kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java
kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/SynchronousQueryProcessorTest.java

This fixes a NullPointerException in case of network errors by retrying

fix(kayenta): Retry in case of network errors

---

kayenta-blobs/src/main/java/com/netflix/kayenta/blobs/storage/BlobsStorageService.java
kayenta-core/src/main/java/com/netflix/kayenta/storage/ObjectType.java
kayenta-gcs/src/main/java/com/netflix/kayenta/gcs/storage/GcsStorageService.java
kayenta-objectstore-configbin/src/main/java/com/netflix/kayenta/configbin/storage/ConfigBinStorageService.java
kayenta-s3/src/main/java/com/netflix/kayenta/s3/storage/S3StorageService.java

- See spinnaker/spinnaker#5134
- Dependent on spinnaker/kork#419 for a Spring Boot dependency upgrade

chore(dependencies): Upgrade Spring Boot to 2.2.1

---

gradle.properties
kayenta-blobs/src/main/java/com/netflix/kayenta/blobs/storage/BlobsStorageService.java
kayenta-core/src/main/java/com/netflix/kayenta/storage/ObjectType.java
kayenta-gcs/src/main/java/com/netflix/kayenta/gcs/storage/GcsStorageService.java
kayenta-objectstore-configbin/src/main/java/com/netflix/kayenta/configbin/storage/ConfigBinStorageService.java
kayenta-s3/src/main/java/com/netflix/kayenta/s3/storage/S3StorageService.java

Revert "chore(dependencies): Upgrade Spring Boot to 2.2.1 (#637)"
This reverts commit e2b1d7b4

chore(dependencies): Reverting Spring Boot 2.2 upgrade

---

gradle.properties

Bump orca version for: https://github.com/spinnaker/spinnaker/issues/5323

chore(orca): Bump orca version to get kork fix.

---

kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
kayenta-blobs/src/main/java/com/netflix/kayenta/blobs/storage/BlobsStorageService.java
kayenta-blobs/src/test/java/com/netflix/kayenta/blobs/storage/TestableBlobsStorageServiceTest.java
kayenta-core/src/main/java/com/netflix/kayenta/security/AccountCredentialsRepository.java
kayenta-core/src/main/java/com/netflix/kayenta/security/CredentialsHelper.java
kayenta-core/src/main/java/com/netflix/kayenta/security/MapBackedAccountCredentialsRepository.java
kayenta-core/src/test/groovy/com/netflix/kayenta/security/MapBackedAccountCredentialsRepositoryTest.java
kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/metrics/DatadogMetricsService.java
kayenta-gcs/src/main/java/com/netflix/kayenta/gcs/storage/GcsStorageService.java
kayenta-graphite/src/main/java/com/netflix/kayenta/graphite/metrics/GraphiteMetricsService.java
kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/metrics/InfluxDbMetricsService.java
kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/metrics/NewRelicMetricsService.java
kayenta-objectstore-configbin/src/main/java/com/netflix/kayenta/configbin/storage/ConfigBinStorageService.java
kayenta-objectstore-memory/src/main/java/com/netflix/kayenta/memory/storage/MemoryStorageService.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
kayenta-prometheus/src/test/java/com/netflix/kayenta/prometheus/integration/CanaryAnalysisPrometheusMetricsMixerServiceIntegrationTest.java
kayenta-s3/src/main/java/com/netflix/kayenta/s3/storage/S3StorageService.java
kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/metrics/SignalFxMetricsService.java
kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/metrics/StackdriverMetricsService.java
kayenta-wavefront/src/main/java/com/netflix/kayenta/wavefront/metrics/WavefrontMetricsService.java
kayenta-web/src/test/java/com/netflix/kayenta/controllers/CanaryConfigControllerTest.java

And replace all duplicated code with the newly introduced method.

feat(core): Introduce getRequiredOne method for AccountCredentialsRepository

---

kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryClassifierConfig.java
kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryClassifierThresholdsConfig.java
kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryJudgeConfig.java
kayenta-core/src/main/java/com/netflix/kayenta/domain/standalonecanaryanalysis/CanaryAnalysisExecutionRequestScope.java

update swagger docs for CanaryClassifierConfig,CanaryClassifierThresholdsConfig, CanaryJudgeConfig, CanaryAnalysisExecutionRequestScope

feat(core): update swagger docs for some of the classes

---

kayenta-integration-tests/src/test/resources/application-base.yml

enhance(integration-tests): remove deprecated properties usage

---

docs/faq.md

This question keeps coming up in Slack.
In the spirit of DRY, I am adding it to the FAQ.

chore(docs): added new entry on using custom profiles for Halyard to the FAQ

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/release_info.sh
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
kayenta-bom/kayenta-bom.gradle
kayenta-core/src/main/java/com/netflix/kayenta/events/listeners/ExecutionArchivalListener.kt
kayenta-graphite/kayenta-graphite.gradle
kayenta-signalfx/kayenta-signalfx.gradle
kayenta-web/kayenta-web.gradle

updates to gradle 6.3
updates to kotlin 1.3.70
updates github actions workflows for new release flags

chore(build): update to newer spinnaker project plugin

---

kayenta-core/kayenta-core.gradle
kayenta-web/kayenta-web.gradle
kayenta-web/src/main/java/com/netflix/kayenta/config/ApplicationConfiguration.java

This PR makes Kayenta pluggable, similar to spinnaker/clouddriver#4383

feat(plugins): plugin support for kayenta

---

gradle.properties
kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/AdminController.java
kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/PipelineController.java

chore: manually bump keiko to 3.7.4 and fix imports

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action

chore(build): enable Gradle wrapper validation (GitHub Actions)

---

gradle.properties
kayenta-core/src/main/java/com/netflix/kayenta/canary/providers/metrics/QueryConfigUtils.java
kayenta-core/src/main/java/com/netflix/kayenta/events/listeners/ExecutionArchivalListener.kt
kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/metrics/SignalFxMetricsService.java
kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/metrics/SimpleSignalFlowProgramBuilder.java

This includes updates to google-java-format and ktlint, so requires some
formatting changes. These were made with a simple `./gradlew spotlessApply`.

chore(spotless): upgrade spinnaker gradle plugin

---

kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/service/CanaryAnalysisService.java

`CanaryAnalysisExecutionStatusResponse`'s `parentPipelineExecutionId` is always null.
Also simplified setting of other parameters to `CanaryAnalysisExecutionStatusResponse` using `map` method:
```
public <U> Optional<U> map(Function<? super T, ? extends U> mapper) {
Objects.requireNonNull(mapper);
if (!isPresent()) {
return empty();
} else {
return Optional.ofNullable(mapper.apply(value));
}
}
```
Since it already wraps nullable object into `Optional.ofNullable` there is no need to wrap it manually.

fix(standalone-canary-analysis): set parent pipeline execution id into standalone canary analysis response

---

Dockerfile

Fixes #794 and #814
Applies the suggestion from https://github.com/spinnaker/kayenta/issues/794#issuecomment-698872876

Get Docker builds working

---

.github/workflows/pr.yml

Adding parallel jobs to execute the different integration test of each provider,
and execute just functional test on the build job https://github.com/spinnaker/kayenta/issues/751

feat(build): adding parallel test for integration tests

---

kayenta-core/src/main/java/com/netflix/kayenta/retrofit/config/RetrofitClientFactory.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/config/PrometheusConfiguration.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/config/PrometheusManagedAccount.java
kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/security/PrometheusCredentials.java
kayenta-web/config/kayenta.yml

Adding bearer token support for prometheus

feat(prometheus): add bearer token support

---

.idea/compiler.xml
.idea/gradle.xml
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/domain/CanaryAnalysisExecutionRequestScope.java
kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/orca/stage/SetupAndExecuteCanariesStage.java
kayenta-standalone-canary-analysis/src/test/java/com/netflix/kayenta/standalonecanaryanalysis/orca/stage/SetupAndExecuteCanariesStageTest.java

Slight tweaks on #824 + a unit test
closes #824 
fixes https://github.com/spinnaker/spinnaker/issues/6239

feature(Kayenta Standalone): allow specifying a control offset in standalone kayenta

---

kayenta-integration-tests/kayenta-integration-tests.gradle

Bumped test container deps so that the integration tests will run

fix(integration-tests): update test container deps

---

build.gradle
gradle.properties
kayenta-bom/kayenta-bom.gradle
kayenta-core/kayenta-core.gradle
kayenta-gcs/kayenta-gcs.gradle
kayenta-graphite/kayenta-graphite.gradle
kayenta-orca/kayenta-orca.gradle
kayenta-signalfx/kayenta-signalfx.gradle
kayenta-web/kayenta-web.gradle

chore(deps): update orca to 8.15.0, use new maven coordinates

---

kayenta-integration-tests/kayenta-integration-tests.gradle
kayenta-integration-tests/src/test/java/com/netflix/kayenta/configuration/EmbeddedGraphiteBootstrapConfiguration.java

Motivated by https://github.com/spinnaker/kayenta/runs/4386204391?check_suite_focus=true from https://github.com/spinnaker/kayenta/pull/854.

Testcontainers cleanup

---

build.gradle
kayenta-graphite/kayenta-graphite.gradle
kayenta-signalfx/kayenta-signalfx.gradle

see https://status.bintray.com/

chore(build): remove references to bintray since it's gone

---

kayenta-graphite/kayenta-graphite.gradle
kayenta-integration-tests/kayenta-integration-tests.gradle
kayenta-signalfx/kayenta-signalfx.gradle

This change makes the project compatible with Gradle 7

chore(build): Gradle 7 compatibility

---

kayenta-core/kayenta-core.gradle

https://nvd.nist.gov/vuln/detail/CVE-2022-42889 see for details.

fix(security): Bump commons-text for CVE-2022-42889

---

kayenta-web/kayenta-web.gradle
kayenta-web/src/main/java/com/netflix/kayenta/Main.java

Using `com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder` class to setup spring and other related properties required for the spring boot application to start.

chore(web): clean up for spring property setup

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.java11.slim
Dockerfile.java11.ubuntu
Dockerfile.slim
build.gradle
gradle.properties

Number 9...
https://github.com/spinnaker/rosco/pull/1047 etc

feat(java17): use JRE17, run tests on JRE17, compile with JDK11

---

kayenta-core/kayenta-core.gradle

Removes some older deps - tests are passing and couldn't find anyplace these were actually utilized.

chore(deps): Remove what is unused dep and bump commons text

---

kayenta-core/src/main/java/com/netflix/kayenta/retrofit/config/RetrofitClientConfiguration.java

Please refer https://github.com/spinnaker/orca/pull/4524

refactor(retrofit): add SpinnakerServerExceptionHandler
