spinnaker/kayenta

- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MeanInequalityClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/preprocessing/Transforms.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/utils/MapUtils.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/TransformSuite.scala
This change makes it possible to specify a NaN replacement strategy, in addition to the (default) removal policy we now have.  It will replace with 0, which is currently the only sane value to replace it with.
> feat(judge): implement NaN replacement strategy

- kayenta-core/src/main/java/com/netflix/kayenta/canary/results/CanaryAnalysisResult.java
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/WeightedSumScorer.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/utils/MapUtils.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ScorerSuite.scala
Implement a new metric feature that indicates if a metric should be report-only, normal, or critical.  Critical metrics which fail cause the entire canary to fail with a 0.0 score, although group scores will be reported normally.  report-only metrics are ignored entirely, including in any counts of number of passes, highs, lows, etc.
> feat(judge): Implement criticality

- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/service/DatadogRemoteService.java
- kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/service/PrometheusRemoteService.java
Just a small initial commit to get my feet wet.
Fixes the link to api docs for Prometheus and added a similar link for datadog in comments.
Please review.
comment-fix
> chore(comments): fixed comments pointing to metric source api docs

- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MeanInequalityClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/RandomClassifier.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ClassifierSuite.scala
This is a temporary fix to cause the classifiers to treat empty arrays as a pass when NaN replacement is enabled.  This should be handled at a higher level, but that is a more sweeping change.  This fixes the defect for now, while I work on the proper fix.
> fix(judge): for NaN replacement, nodata means pass

- kayenta-judge/kayenta-judge.gradle
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/preprocessing/Transforms.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/utils/RandomUtils.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ClassifierSuite.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/TransformSuite.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/UtilsSuite.scala
Handle the scenario (degenerate distribution) where the ranks, as computed by Mann-Whitney, are tied resulting in an `Error` classification as discussed in #301 . 
To address this, we add a small amount of [Gaussian white noise](https://en.wikipedia.org/wiki/White_noise) to the input signal when both the experiment and control signals are constant.
> fix(judge): Handle tied ranks by adding Gaussian white noise

- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MeanInequalityClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/RandomClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/score/ThresholdScoreClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/BaseScorer.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/WeightedSumScorer.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ClassifierSuite.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ScorerSuite.scala
Check the critical Effect Size (Mean Ratio) after classifying the metric. The critical Effect Size is configurable and is used to set the maximum difference allowed between the experiment and control metric. If this difference is exceeded, and the metric is marked as critical, then the entire canary will be marked as a failure and a score of zero returned.
> feat(judge): Implement critical effect size check

- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryClassifierConfig.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryExecutionRequest.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java
- kayenta-core/src/main/java/com/netflix/kayenta/controllers/CanaryJudgesController.java
Remove thresholds from canary configs, as they are specified by Spinnaker, and make more sense in general to be runtime parameters.  Having them in two places also causes confusion for users.
A similar PR will be made to remove this from the canary config UI.
> feat(thresholds): require on execution, remove from config

- kayenta-web/src/main/java/com/netflix/kayenta/config/WebConfiguration.java
- kayenta-web/src/main/java/com/netflix/kayenta/filters/KayentaCorsFilter.java
This will echo back the contents of the `Origin` header, if present, and add additional CORS headers.  No checking is done on the origin; this could be added later if needed.
> feat(cors-headers): add if we have an Origin header on request

- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/backends/BackendDatabase.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/config/AtlasConfiguration.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/model/Backend.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/security/AtlasCredentials.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/security/AtlasNamedAccountCredentials.java
- kayenta-atlas/src/test/java/com/netflix/kayenta/atlas/BackendTest.java
- kayenta-atlas/src/test/java/com/netflix/kayenta/atlas/BackendsTest.java
- kayenta-atlas/src/test/resources/com/netflix/kayenta/atlas/backends-location-test.json
- kayenta-core/src/main/java/com/netflix/kayenta/security/AccountCredentials.java
- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/metrics/DatadogMetricsService.java
- kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/metrics/InfluxDbMetricsService.java
- kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
- kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/metrics/StackdriverMetricsService.java
- kayenta-web/config/kayenta.yml
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/MetricSourceDetail.java
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/MetricSourcesController.java
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/MetricsServiceDetail.java
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/MetricsServicesController.java
This is a partial fix for some Atlas complexity reduction.
This adds an ability to provide UI hints about locations.  For Atlas, Netflix has many deployment, environment, and datacenter combinations to choose from.  We have started changing to a model where these magic location strings will be sufficient to provide all these details, as they are unique across all our atlas deployments.
With this change, most of the special Atlas scope parameters will be replaced by the single location, which will greatly simplify the code.
Optionally, a recommended list may be provided in the kayenta config YAML file. If provided, it will be inserted into the `recommendedLocations` list; otherwise, the list should be empty.
I recommend the UI to present a text input box if `locations` is empty, otherwise …
> feat(locations): provide location hints for atlas

- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/backends/BackendDatabase.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/model/Backend.java
- kayenta-atlas/src/test/java/com/netflix/kayenta/atlas/BackendTest.java
- kayenta-atlas/src/test/java/com/netflix/kayenta/atlas/BackendsTest.java
A previous change was able to generate a list of potential location values to be used by back-ends.  This change uses that in the Atlas code base to look up the specific URI to use for that location string.
This will fall-back to previous behavior if it is not set, and will look in the Atlas-specific context for "dataset", "deployment", and "environment" and use location as the region.
I do not like the big if/else block in Backend.json, but I could not think of a more elegant solution.  I have a test case for all four possibilities, including a no-match for each.
> feat(atlas): Map locations forward to a specific back-end

- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ClassifierSuite.scala
Return a reason string when a metric is classified as Nodata.
> fix(judge): Return a reason when a metric is classified as Nodata

- build.gradle
- gradle/buildViaTravis.sh
- gradle/init-publish.gradle
- gradle/installViaTravis.sh
- kayenta-web/kayenta-web.gradle
Removes spring boot gradle plugin. 
Ref: https://github.com/spinnaker/spinnaker/issues/2844
> chore(builds): Introduces composite builds via gradle plugin

- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
- kayenta-core/src/main/java/com/netflix/kayenta/util/Retry.java
- kayenta-core/src/test/groovy/com/netflix/kayenta/util/RetrySpec.groovy
- kayenta-objectstore-configbin/src/main/java/com/netflix/kayenta/configbin/storage/ConfigBinStorageService.java
- kayenta-s3/src/main/java/com/netflix/kayenta/s3/storage/S3StorageService.java
While I would like a more general approach, and this is not quite as clean as I'd like, it's a step toward getting things closer to sane.
I don't yet have metrics wired up, but will add this eventually; I may also split out the "call this method until it stops throwing exceptions" type of call now into a more sane context (http, atlas) aware retry system.  For now, this will work better than what was there.
> Add more retries to more components

- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionRequest.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/RunCanaryContext.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/orca/stage/SetupAndExecuteCanariesStage.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/orca/task/RunCanaryTask.java
Add siteLocal map to standalone canary analysis request and propagate it to the individual canary executions as well, so that notification metadata can be passed to external event listeners.
> feat(standalone-canary-analysis): Add siteLocal map to standalone canary analysis request

- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/domain/CanaryAnalysisExecutionResponse.java
Add more constructers to CanaryAnalysisExecutionResponse so that it can be deserialized with Jackson
> add more constructers to CanaryAnalysisExecutionResponse so that it can be deserialized with Jackson

- kayenta-signalfx/kayenta-signalfx.gradle
- kayenta-signalfx/src/integration-test/java/com/netflix/kayenta/config/SignalFxMockServiceReportingConfig.java
- kayenta-signalfx/src/integration-test/java/com/netflix/kayenta/signalfx/EndToEndCanaryIntegrationTests.java
- kayenta-signalfx/src/integration-test/java/com/netflix/kayenta/signalfx/EndToEndStandaloneCanaryAnalysisIntegrationTests.java
- kayenta-signalfx/src/integration-test/resources/config/kayenta.yml
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/canary/SignalFxCanaryScope.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/canary/SignalFxCanaryScopeFactory.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxConfiguration.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxManagedAccount.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxScopeConfiguration.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/metrics/SignalFxMetricsService.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/metrics/SimpleSignalFlowProgramBuilder.java
- kayenta-signalfx/src/test/java/com/netflix/kayenta/signalfx/metrics/SimpleSignalFlowProgramBuilderTest.java
This PR makes including `_scope_key` in the extendedScopeParameters optional and allows operators to define account / org wide defaults.
This PR also adds the location to the query if it is supplied as an account default or in the extendedScopeParameters as `_location_key`.
Both changes are backwards compatible.
> feat(signalfx): add optional default scope and location keys when configuring accounts

- kayenta-gcs/kayenta-gcs.gradle
- kayenta-google/kayenta-google.gradle
- kayenta-stackdriver/kayenta-stackdriver.gradle
A few kayenta modules pull in the GCE client library, which is unused. In preparation for bumping the library, remove it from unused places.
> chore(google): Clean up google dependencies

- gradle.properties
- kayenta-core/kayenta-core.gradle
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryArchiveResultUpdateResponse.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryExecutionStatusResponse.java
- kayenta-core/src/main/java/com/netflix/kayenta/events/CanaryExecutionCompletedEvent.java
- kayenta-core/src/main/java/com/netflix/kayenta/events/listeners/ExecutionArchivalListener.kt
- kayenta-core/src/main/java/com/netflix/kayenta/storage/ObjectType.java
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryController.java
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryResultArchiveController.java
This change allows execution details to be removed from the Redis-backed execution repository, yet still return JSON data from object storage.  This makes the redis footprint smaller while still maintaining long-lived links to canary reports or raw data.
Use object storage to archive the same response we'd give back for `GET /canary/:id`.  Add a controller to manipulate these archive objects.  The controller is documented as not intended to be used directly.
In the CanaryController, first look in redis for the execution information, and if found return it as usual.  If not found, look in the archive and return what we have from that.
> feat(canary-results): archive exactly what we return via HTTP

- gradle.properties
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryController.java
* chore(orca): Bump Orca to 6.139.0
* fix(canary/orca): Replace limit with pageSize 
The `limit` parameter was replaced with `pageSize` in
spinnaker/orca#2593
> fix(orca): Update Orca to 6.139.0

- gradle.properties
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryController.java
* chore(orca): Bump Orca to 6.139.0
* fix(canary/orca): Replace limit with pageSize
The `limit` parameter was replaced with `pageSize` in
https://github.com/spinnaker/orca/pull/2593
> fix(orca): Update Orca to 6.139.0 (#496)

- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryExecutionRequest.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryScope.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryScopePair.java
- kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricSetMixerService.java
- kayenta-core/src/main/java/com/netflix/kayenta/metrics/orca/MetricSetMixerServiceTask.java
- kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/MetricSetMixerServiceSpec.groovy
- kayenta-graphite/src/integration-test/java/com/netflix/kayenta/graphite/E2EIntegrationTest.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/orca/stage/SetupAndExecuteCanariesStage.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/orca/task/RunCanaryTask.java
Potentially breaking change:  I'm not sure all metric services will behave properly here.
Real world bug this fixes:  One of control/experiment has data with tags, the other has no data and Atlas fakes up a placeholder metric.  When these are paired, the metric mixer then generates empty arrays for the tags AND for the empty tag list "metric" we faked up to pair.  The judge currently expects arrays of NaNs, not empty arrays, as its contract.
This restructures how the mixer service works, which currently uses a placeholder that the metric service must insert when no data was returned.  This feels like we could instead use the metric's runtime scope to derive the number of points expected, but that means we would lose the query attributes for the UI to provide.  Additionally, while the …
> fix(MixerService): properly handle missing metrics

- kayenta-signalfx/src/integration-test/resources/integration-test-canary-config.json
This adds a couple metrics to the integration test canary config that massages logic around when metrics do not report data. 
I made this to test https://github.com/spinnaker/kayenta/pull/499, the integration tests still pass as expected.
> refactor(signalfx): add additional test metrics to integration canary config

- kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
- kayenta-prometheus/src/test/java/com/netflix/kayenta/prometheus/integration/CanaryAnalysisPrometheusMetricsMixerServiceIntegrationTest.java
fixes #522 
fixes #524 
The Prometheus metrics service was not supplying the end time data which is marked as not nullable.
> fix(prometheus): Canary Analysis fails with Illegal Argument Exception.

- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/backends/AtlasStorageDatabase.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/backends/AtlasStorageUpdater.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/backends/AtlasStorageUpdaterService.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/canary/AtlasCanaryScope.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/canary/AtlasCanaryScopeFactory.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/config/AtlasConfiguration.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/model/AtlasStorage.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/model/Backend.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/security/AtlasNamedAccountCredentials.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/service/AtlasStorageRemoteService.java
Add support for going from an accountId (usually an AWS account ID string) to an atlas backend which stores data for that account.
This change adds another magic URL (which I should document) to the Atlas back-end.  This database consists of a set of account IDs to Atlas back-ends.  This makes kayenta-atlas more Netflix specific, but I can address this later should anyone show interest in using Atlas outside of Netflix.
> feat(atlas): Find atlas back-end by accountId

- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/stats/EffectSizes.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ClassifierSuite.scala
- kayenta-judge/src/test/scala/com/netflix/kayenta/judge/StatisticSuite.scala
In the scenario where the experiment or control metric has a mean of zero, the effect size (mean ratio) should not be computed and should be reported as NaN. In addition, the effect size comparison should be ignored when the statistic cannot be computed.
> fix(judge): Incorrect Effect Size with Zero Means (#510)

- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/metrics/DatadogMetricsService.java
**fix(datadog): Support placeholder metrics in `DatadogMetricsService`**
DatadogMetricsService currently returns an empty `List<MetricSet>` if no metrics can be found for some `canaryConfig` and `scope`.  This can result in complete CanaryAnalysis stage failure if one metric cannot be found for a CanaryConfig.
This can be frustrating in several cases:
- An application chooses to stop publishing a metric, but does not update the CanaryConfig.
- An application publishes some, but not all, metrics needed for a shared CanaryConfig that it references.
Kayenta already gracefully supports a lack of MetricSet values. This change will leverage that support by creating an empty placeholder metric when Datadog fails to return any metric.
References:
[Stackdriver placeholder …
> fix(datadog): Create MetricSet placeholder

- kayenta-web/kayenta-web.gradle
according to [gradle docs](https://docs.gradle.org/5.3.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management)
`runtime` is a deprecated scope and we should be using `runtimeOnly`
> chore(core): replace runtime with runtimeOnly in kayenta-web.gradle

- kayenta-signalfx/README.md
- kayenta-signalfx/src/integration-test/resources/config/kayenta.yml
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxConfiguration.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxManagedAccount.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/service/SignalFxRequestError.java
Fixes #549 
Context: This metric source originally had support for this like the other metrics sources, but I couldn't find evidence at the time (not sure if realms are new or not) that the endpoint ever changed. So I had removed the configurable option and hard coded the endpoint url. [See this conversation for more details.](https://github.com/spinnaker/kayenta/pull/385#discussion_r225203024) This PR brings it back since someone has asked for it.
> feat(signalfx): Add configurable remote baseurls to support realms.

- kayenta-web/config/kayenta.yml
`management.security.enabled` is removed from Spring Boot 2.
> fix(kayenta): Fix management endpoints configuration after migration to Spring Boot 2

- build.gradle
- kayenta-bom/kayenta-bom.gradle
Fixes generated pom.xml to omit invalid declaration of lombok dependency.
compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
Current `pom.xml` of any kayenta-* dependency is broken and leads to the following output when is used in Maven project:
```
[WARNING] The POM for com.netflix.kayenta:kayenta-web:jar:2.2.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```
`kayenta-web` pom.xml contains the following invalid declaration:
The issue with publishing compileOnly dependencies was fixed in latest `nebula-publishing-plugin` (https://github.com/nebula-plugins/nebula-publishing-plugin/commit/a5432aadc4b2886f1d9 …
> fix(kayenta): Fixes generated pom.xml to omit invalid declaration of lombok

- build.gradle
fix(kayenta): remove spring-boot-properties-migrator from depedencies as not needed after migration to Spring Boot 2
> fix(kayenta): remove spring-boot-properties-migrator from depedencies

- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/canaryanalysis/controller/StandaloneCanaryAnalysisController.java
fix(standalone_canary_analysis): use the supplied user when present.
> fix(standalone_canary_analysis): use the supplied user when present.

- cloudbuild.yaml
Add a cloudbuild.yaml file that reproduces the one generated on-the-fly during the official build process.
> chore(build): Add cloudbuild.yaml file

- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryExecutionStatusResponse.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/orca/task/MonitorCanaryTask.java
- kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryController.java
This PR adds the metric account used for the canary to the canary status response, so that we can have a modify and retry button in our retrospective analysis tool / reports.
I also did some misc clean up in the Execution Mapper for the canary status response. Mainly extracting some duplicated code into a method and converting some if then blocks into optional chains.
> feat(canary): Add additional metadata to the canary status response.

- kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/config/NewRelicConfiguration.java
- kayenta-web/config/kayenta.yml
There's a couple of reasons for this: 1) we need to be able to configure this endpoint for staging, 2) this is the convention that the other providers follow; there's no reason to have this be hardcoded as a constant and not configurable.
> refactor(newrelic): get nr endpoint from config

- docker-compose.yaml
Running in standalone mode, `kayenta` was not able to connect to the running `redis` instance.
Prior to the PR, the following error was seen
`kayenta_1  | Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379`
> fix(docker): docker compose fixes

- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/metrics/SignalFxMetricsService.java
We noticed that in Signal Fx if you have metrics that are reporting at differing frequencies. 
Say a system agent on an EC2 instance that reports system cpu and memory at 1 data point per minute and application metrics that report 6 times per minute.
In Kayenta if you set the step to 10 (6 datapoints per minute) that the CPU and Memory data gets padded with a bunch of NaNs and gets graphed weird.
Just taking that data and stretching it had some side effects as well, so this PR adds more attributes to the data that flows through with the results so that the data can be reconstructed and graphed more accurately.
Before:
After:
CC: @melanahammel
> feat(signalfx): Provide additional context about the results of the signalflow programs.

- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala
Adds the ability to re-enable outlier removal on a per-metric basis:
```
{
"name": "5xx rate",
"query": {
"type": "prometheus",
"customInlineTemplate": "PromQL:avg(rate(gateway_http_responses{code=\"5xx\", pod=~\"$\\{scope}\"}[2m]))",
"serviceType": "prometheus"
},
"groups": [
"Group 1"
],
"analysisConfigurations": {
"canary": {
"outlierStrategy":"remove"
}
},
"scopeName": "default"
},
```
> fix(judge): Disable first pass outlier removal by default.

- Dockerfile
- Dockerfile.slim
The container we had been using hasn't been updated in months. See
spinnaker/spinnaker#5204.
> chore(release): Use the alpine containers instead of openjdk

- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/config/AtlasSSEConverter.java
- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
When an Atlas a metric's query string for Atlas results in a query error, the current error message lacks context about which metric, and which config are at fault. This change adds those details to the error message.
- Create a new instance of the Atlas converter for each query, and provide it with the unique query context information required for enriching the error log, should an error arise.
- Add config name, query name, and query string to the Atlas converter instance
- Include them in the error message when atlas responds with an `IllegalStateError` (bad Atlas query), so it's easier to trace it back to the specific query for troubleshooting.
**Before**:
```
retrofit.RetrofitError: Atlas query failed: IllegalStateException: no matches for word ':and' with stack [Equal], candidates: …
```
> feat(Kayenta/Atlas): Add context to atlas query error message

- docs/canary-config.md
`canary.nanStrategy` defaults to `remove` as seen here: https://github.com/spinnaker/kayenta/blob/master/kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala#L54
This PR updates the docs to indicate this field is optional, not required, and specifies the default value.
> chore(docs): update nanStrategy from required to optional

- kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryJudgesController.java
CanaryJudgesController is the only controller that is located in kayenta-core module. All other Kayenta web endpoints are located in kayenta-web.
> feat(core): move CanaryJudgesController to kayenta-web module

- kayenta-core/kayenta-core.gradle
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryConfig.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryMetricSetQueryConfig.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryScope.java
- kayenta-core/src/main/java/com/netflix/kayenta/canary/providers/metrics/QueryConfigUtils.java
- kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsService.java
- kayenta-core/src/test/groovy/com/netflix/kayenta/canary/providers/metrics/QueryConfigUtilsSpec.groovy
- kayenta-core/src/test/groovy/com/netflix/kayenta/canary/providers/metrics/QueryConfigUtilsTest.java
- kayenta-core/src/test/groovy/com/netflix/kayenta/canary/providers/metrics/TestCanaryMetricSetQueryConfig.groovy
- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/metrics/DatadogMetricsService.java
- kayenta-graphite/src/main/java/com/netflix/kayenta/graphite/metrics/GraphiteMetricsService.java
- kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/metrics/NewRelicMetricsService.java
- kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/metrics/NewRelicQueryBuilderService.java
- kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
- kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/metrics/StackdriverMetricsService.java
- kayenta-stackdriver/src/test/groovy/com/netflix/kayenta/providers/metrics/StackdriverCanaryMetricSetQueryConfigSpec.groovy
Freemarker is very powerful template engine, but in Kayenta only 1 percent of it's capabilities are actually used. For template expanding with map of variables simple string substitutor does the trick.
Also this change allowed to remove `throws IOException` from the signature of `MetricsService.buildQuery`.
Added tests for all basic scenarios of `QueryConfigUtils`.
> Replace freemarker with stringsubstitutor from commons-text for template expanding

- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
The `eval()` call to Mann-Whitney is deprecated. Update to use `mannWhitneyUTest()`.
> fix(judge): Update deprecated call to Mann-Whitney

- kayenta-core/src/main/java/com/netflix/kayenta/domain/standalonecanaryanalysis/StageMetadata.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/service/CanaryAnalysisService.java
- Implementation of #671 
- Updates `StageMetadata` to have the execution ids available for canary intervals for standalone canary analysis
> feat(standalone-canary-analysis): add executions ids to stage metadata

- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/orca/task/RunCanaryTask.java
When I retrieve results for the standalone canary analysis via archive endpoint I see that `parentPipelineExecutionId` is already set, but I haven't provided it. This PR fixes `parentPipelineExecutionId` to be equal to the one that was set by the user.
@fieldju could you please review?
> fix(standalone-canary-analysis): custom parent pipeline execution id is not used

- gradle.properties
- kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/config/PrometheusResponseConverter.java
* fix(prometheus): Prometheus can return "+Inf" and "-Inf" as values for metrics. This fixes java.lang.NumberFormatException in such cases.
> fix(prometheus): Handle +Inf/-Inf from Prometheus

- kayenta-aws/src/main/java/com/netflix/kayenta/aws/config/AwsManagedAccount.java
- kayenta-google/src/main/java/com/netflix/kayenta/google/config/GoogleManagedAccount.java
Halyard is defaulting the AWS and Google accounts' rootFolder to "kayenta." Since kleat will not provide such defaults, let's move the default from config into code. This will not change behavior for Halyard users relying on the default, or any users setting their own rootFolder in config.
> feat(config): default AWS and Google rootFolder to `kayenta`

- halconfig/README.md
- halconfig/kayenta.yml
- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/config/DatadogManagedAccount.java
- kayenta-newrelic-insights/src/main/java/com/netflix/kayenta/newrelic/config/NewRelicManagedAccount.java
- kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/config/PrometheusManagedAccount.java
- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxManagedAccount.java
- kayenta-web/config/kayenta.yml
* refactor(config): move Halyard defaults into code 
Halyard currently defaults the `supportedTypes` list of Datadog, Prometheus, SignalFx, and New Relic accounts to a singleton list including type METRICS_STORE, which is the only reasonable choice for these account types. Let's lift that defaulting into the classes themselves, so that Kleat does not need to set them. While I think this would also be a reasonable default to set for the other metrics-only accounts, this change is limited to those accounts currently configurable using Halyard.
* refactor(config): deprecate Halyard-specific config file 
Lifts the redis endpoint from the Halyard-specific config to the base config. This should not impact existing Halyard or non-Halyard users.
> refactor(config): move Halyard defaults into code and deprecate Halyard-specific config

- kayenta-core/src/main/java/com/netflix/kayenta/storage/ObjectType.java
- kayenta-core/src/main/java/com/netflix/kayenta/storage/StandardObjectType.java
make ObjectType an interface instead of enum to be able to use StorageService for some custom object types
> refactor(core): make ObjectType an interface instead of enum

- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/config/DatadogConfigurationProperties.java
- kayenta-web/config/kayenta.yml
Document the metadataCachingIntervalMS setting which can be set in the service-local.yaml - update datadog poller default to 15 minutes due to api limits
> fix: document metadataCachingIntervalMS in kayenta.yaml

- kayenta-core/src/main/java/com/netflix/kayenta/config/KayentaConfiguration.java
- kayenta-core/src/main/java/com/netflix/kayenta/config/KayentaSerializationConfigurationProperties.java
- kayenta-core/src/main/java/com/netflix/kayenta/retrofit/config/RetrofitClientConfiguration.java
- kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/CanaryScopeSpec.groovy
- kayenta-core/src/test/groovy/com/netflix/kayenta/util/KayentaSerializationConfigurationPropertiesTest.groovy
- kayenta-web/config/kayenta.yml
A recent change to the `springboot.jackson.ObjectMapper`'s serialization behaviour changed the way `canaryDuration` is serialized in canary reports. This PR adds a configuration section to control that behaviour, and sets to default to match the behaviour before the change.
Jackson 2.10+ changes the default behaviour for serializing Duration from String to Timestamp.
The behaviour is already being set explicitly for Date objects, but wasn't addressed for Duration objects.
Rather than setting this property explicitly, I added a configuration stanza to `kayenta.yml` to allow users to set their preferred behaviour, and defaulting to the old behaviour of encoding both Date and Duration as Strings.
Before (with the updated serialization behaviour):
```
"canaryDuration": 1800000
```
After (with …
> config(kayenta-core): Add KayentaSerializationConfigurationProperties

- kayenta-integration-tests/kayenta-integration-tests.gradle
- kayenta-integration-tests/src/test/java/com/netflix/kayenta/configuration/MetricsReportingConfiguration.java
This PR: https://github.com/spinnaker/kayenta/pull/708/files disabled integration tests and they have not been running since April, when I thought they had been.
This PR reverses the logic to make them opt-out rather than opt-in so they do not get accidentally disabled.
> fix(build): renable and reverse logic to prevent the accidental disabling of integration tests

- kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java
We were hitting a strange end case (usually associated with a timeout) where the cause was not an IOException but the response was null. This was often associated with a read timeout, which is probably not safe to retry.
First time touching this code. Happy for any and all feedback.
> fix(retry): Retry logic wasn't properly checking the response for nulls

- kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java
- kayenta-web/src/test/java/com/netflix/kayenta/controllers/BaseControllerTest.java
- kayenta-web/src/test/java/com/netflix/kayenta/controllers/CanaryControllerTest.java
This addresses a bug we discovered when running a config with no metrics. Orca would retry indefinitely waiting for non existent stages to complete.
Added a test on one of the controllers. Adding the check to the executionMapper seemed to be the safest spot since there seems to be an abundant number of ways to trigger a canary. 
Happy to adjust things. Just let me know.
> Fix Canary Indefinitely Retrying

- kayenta-web/src/main/java/com/netflix/kayenta/controllers/CanaryController.java
We are not doing anything with this yet in the UI, but we may want to allow users to view paginated result sets. This simply exposes the underlying pagination feature provided by Orca.
> feat(reports): allow pagination of canary reports endpoint results

- Dockerfile
As title. The `MAINTAINER` label is deprecated and now we should use `LABEL` instead.
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
> chore(dockerfile): change deprecated maintainer instructor to label

- kayenta-objectstore-configbin/src/main/java/com/netflix/kayenta/configbin/storage/ConfigBinStorageService.java
When using ConfigBin (i.e. working at Netflix), all the canary configs appear to have been updated very recently (but not all at the same time). It's because of [this block of code in the CanaryConfigIndexingAgent](https://github.com/spinnaker/kayenta/blob/master/kayenta-core/src/main/java/com/netflix/kayenta/index/CanaryConfigIndexingAgent.java#L156-L163):
```java
Long updatedTimestamp = (Long) canaryConfigSummary.get("updatedTimestamp");
String updatedTimestampIso =
(String) canaryConfigSummary.get("updatedTimestampIso");
if (updatedTimestamp == null) {
updatedTimestamp = canaryConfigIndex.getRedisTime();
updatedTimestampIso = Instant.ofEpochMilli(updatedTimestamp).toString();
}
```
This will work a lot better when we supply the `updatedTimestamp` to the agent.
> fix(config): include updatedTimestamp when indexing configs

- kayenta-aws/kayenta-aws.gradle
With this, anyone that uses a task role inside EKS will be able to access
S3 buckets granted to them by their task-role.
Fixes #790
> fix(kubernetes): Adding STS Jar to classpath

- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/metrics/SimpleSignalFlowProgramBuilder.java
- kayenta-signalfx/src/test/java/com/netflix/kayenta/signalfx/metrics/SimpleSignalFlowProgramBuilderTest.java
This MR addresses the following two use cases for generating SignalFX SignalFlow which are currently not properly supported.
1. **Negated Filters**
For example, in SignalFX, when building SignalFlow, the following is valid:
```
!app:cms
```
which would translate to the following SignalFlow
```
filter=(not filter('app', 'cms'))
```
However, if you tried to use `!code` when defining the `key` for Query Pairs in Kayenta SignalFX, it would generate the following SignalFlow.
```
filter('!app', 'cms')
```
2. **Multiple QueryPair Values**
In SignalFX, when building SignalFlow, the following is valid:
```
app:cms,api
```
which would translate to the following SignalFlow
```
filter('app', 'cms', 'api')
```
However, if you attempted to do this currently using `cms, api` as the `value` in a …
> Support Negated Filters and Multiple QueryPair values when building SignalFlow

- kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
Currently there is no validation before use the MetricName property, which can produce a NPE if there is no value set
Frontend validation https://github.com/spinnaker/deck-kayenta/pull/548
`java.lang.NullPointerException: null
at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:124) ~[na:na]
at com.netflix.kayenta.prometheus.metrics.PrometheusMetricsService.buildQuery(PrometheusMetricsService.java:211) ~[kayenta-prometheus.jar:na]
at com.netflix.kayenta.prometheus.metrics.PrometheusMetricsService.queryMetrics(PrometheusMetricsService.java:253) ~[kayenta-prometheus.jar:na]`
> fix(prometheus): prevent NPE when metricName isn't set

- kayenta-signalfx/kayenta-signalfx.gradle
- kayenta-signalfx/src/integration-test/java/com/netflix/kayenta/signalfx/EndToEndCanaryIntegrationTests.java
- kayenta-signalfx/src/integration-test/java/com/netflix/kayenta/signalfx/EndToEndStandaloneCanaryAnalysisIntegrationTests.java
- kayenta-signalfx/src/integration-test/resources/integration-test-canary-config.json
- Fixed integration tests that were failing due to timing and query issues
- Upgraded signalfx version to 1.0.5
> chore(signalfx): bump sfx version and fix integration tests

- docs/canary-config.md
- kayenta-core/src/main/java/com/netflix/kayenta/canary/results/CanaryAnalysisResult.java
- kayenta-graphite/kayenta-graphite.gradle
- kayenta-integration-tests/kayenta-integration-tests.gradle
- kayenta-integration-tests/src/test/java/com/netflix/kayenta/metrics/RandomProvider.java
- kayenta-integration-tests/src/test/java/com/netflix/kayenta/tests/standalone/PrometheusStandaloneCanaryAnalysisTest.java
- kayenta-integration-tests/src/test/resources/application-cases.yml
- kayenta-integration-tests/src/test/resources/canary-configs/prometheus/muted-metric.json
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
- kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/ScoringHelper.scala
- kayenta-signalfx/kayenta-signalfx.gradle
We are using canary analysis for lots of services internally in Playtika. Sometimes we need to add new metrics for the analysis and as it turns out -- we don't always start with ideal configuration and as a result it may lead to failed canary analysis. We want users to treat canary analysis as a real indicator of issues with deployment, so ideally we want to enable only the metrics that guarantee correct alarming 100% of the time. The `muted` property gives an ability to analyze metric, but skip it's result in a total score computation, so in case it is not yet perfect we won't affect deployments.
Implementation is backward compatible.
> feat(judge): add ability to mute metric result from total score computation

- kayenta-azure/src/main/java/com/netflix/kayenta/azure/security/AzureCredentials.java
**Why:**
- Kayenta has support for storing objects and metrics in Azure Storage but it's hardcoded to HTTP.
- HTTP is insecure.
- Azure Storage by default supports HTTPS.
**What:**
- Changed `DefaultEndpointsProtocol` to HTTPS
**Issue:**
- https://github.com/spinnaker/spinnaker/issues/6205
> fix(azure): HTTPS support for Azure Storage (spinnaker#6205)

- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/service/DatadogTimeSeries.java
hi there! I noticed that a time series I was getting back from datadog had `null` values in it, leading to NPEs when the code here was trying to populate from the datadog API response. 
I'm not sure if I chose a strange query to use in DD, or maybe my app isn't reporting metrics in to DD properly? But, I figured I'd pose the PR here anyway in case other people run into the same null pointer exception.
Here's an example API response I was getting from Datadog that had `null` values in it:
```
{
"status": "ok",
"res_type": "time_series",
"from_date": 1612350973000,
"series": [
{
"end": 1612351110000,
"attributes": {},
"metric": "(api.request_5xx / api.request_all)",
"interval": 1,
"tag_set": [],
"start": 1612350980000,
"length": 14,
"query_index": 0,
"aggr": "sum",
"scope": …
```
> fix(datadog): check for null values in datadog time series

- kayenta-core/src/main/java/com/netflix/kayenta/config/KayentaConfiguration.java
- kayenta-core/src/main/java/com/netflix/kayenta/events/listeners/ExecutionArchivalListener.kt
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/config/StandaloneCanaryAnalysisModuleConfiguration.java
- kayenta-standalone-canary-analysis/src/main/java/com/netflix/kayenta/standalonecanaryanalysis/event/listener/StandaloneCanaryAnalysisExecutionArchivalListener.java
reverts #837 in favor of just overriding the entire archiver.
> feat: revert pre-hook and just allow for disabling default archivers so that extensions can just override them

- kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/service/DatadogTimeSeries.java
- kayenta-datadog/src/test/java/com/netflix/kayenta/datadog/service/DatadogTimeSeriesTest.java
There was an attempted fix for this earlier (https://github.com/spinnaker/kayenta/pull/832) but it's incorrect. That fix caused every adjusted point to become `NaN` after the first `null` value. As an example, the `handlesNullInPointlist` test case would fail with `java.lang.AssertionError: expected:<[1.0, NaN, 1.0, 1.0, 1.0, NaN, NaN, NaN, NaN, NaN, 1.0]> but was:<[1.0, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]>`
> fix(datadog): fix null handling in DatadogTimeSeries

- kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
Atlas wants this to be `https`.
> fix(atlas): use https for atlas endpoints

- kayenta-graphite/src/main/java/com/netflix/kayenta/graphite/service/GraphiteRemoteService.java
We noticed on newer versions of graphite and certain queries that the target parameter must be properly urlencoded before being sent to the graphite service via GET. Previously we had set this to false as very old versions of graphite did not handle the url encoding properly, I tested this with our graphite and the change seems safe and fixes the bugs we saw in newer graphites.
> fix(graphite): urlencode target query

- build.gradle
- gradle.properties
- kayenta-bom/kayenta-bom.gradle
- kayenta-core/kayenta-core.gradle
- kayenta-gcs/kayenta-gcs.gradle
- kayenta-graphite/kayenta-graphite.gradle
- kayenta-integration-tests/kayenta-integration-tests.gradle
- kayenta-orca/kayenta-orca.gradle
- kayenta-signalfx/kayenta-signalfx.gradle
- kayenta-web/kayenta-web.gradle
There is an issue in the Plugins Framework that was solved in this PR: spinnaker/kork#866
but this fix was released in kork 7.110.0
I bumped the version of kork to include the fix in VersionManager in the plugins framework but this involved changing the groupId of kork because now it's been published under "io.spinnaker" and this release branch is pretty old.
I had to bump the version of Fiat as well because it has issues when trying to download the kork version in fiat due to the groupId change.
> fix(build): bump kork to 7.110.0 & change groupId for dependencies

- gradle.properties
Kayenta is failing with the following exception on startup:
```
2022-02-15 16:33:30.908 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
com.netflix.spinnaker.kork.plugins.config.SpringEnvironmentConfigResolver.<init>(SpringEnvironmentConfigResolver.kt:61)
The following method did not exist:
'void com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(int, boolean, boolean, boolean, com.fasterxml.jackson.module.kotlin.SingletonSupport, int, kotlin.jvm.internal.DefaultConstructorMarker)'
The method's class, com.fasterxml.jackson.module.kotlin.KotlinModule, is …
```
> chore(dependencies): bump orcaVersion to 8.18.2

- Dockerfile
- Dockerfile.compile
- Dockerfile.slim
This resolves a performance issue in JDK11 when Spinnaker is running in
a cluster with containerd.
> chore(dockerfile): upgrade to latest alpine image

- kayenta-integration-tests/kayenta-integration-tests.gradle
since tests fail with testCompileOnly (introduced in https://github.com/spinnaker/kayenta/pull/895, previously testCompile) like:
```
Caused by:
java.lang.NumberFormatException: For input string: "${management.server.port}"
```
but apparently we've gotten numb to integration test failures for one reason or another.
https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
recommends testImplementation instead of testCompile.
> fix(integration-tests): change testCompileOnly dependencies to testImplementation

- kayenta-integration-tests/src/test/resources/application-base.yml
- kayenta-web/config/kayenta.yml
While upgrading the spring-boot by transitively upgrading the orca version (8.26.0) in kayenta and enforcing the dependencies, the kayenta-integration-tests:GraphiteStandaloneCanaryAnalysisTest failed with below error:
```
java.lang.AssertionError: 1 expectation failed.
JSON path executionStatus doesn't match.
Expected: is "SUCCEEDED"
Actual: TERMINAL
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at …
```
> fix(test): Issue with kayenta-integration-tests while upgrading spring-boot to 2.3.12

- gradle.properties
- kayenta-integration-tests/kayenta-integration-tests.gradle
- kayenta-integration-tests/src/test/java/com/netflix/kayenta/tests/BaseIntegrationTest.java
- kayenta-integration-tests/src/test/resources/application-base.yml
- kayenta-orca/src/main/java/com/netflix/kayenta/config/OrcaCompositeHealthContributor.java
- kayenta-orca/src/main/java/com/netflix/kayenta/orca/controllers/PipelineController.java
* Migrate to HealthContributorRegistry
* Add `@AutoConfigureMetrics`. `@SpringBootTest` no longer configures available monitoring systems and only provide the in-memory MeterRegistry. If you were exporting metrics as part of an integration test, you can add `@AutoConfigureMetrics` to your test to restore the previous behaviour. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes
* Upgrade embedded testcontainers. `testcontainers-spring-boot` project migrated to Spring Boot 2.4 in 2.0.0 version. In order to use this project with Spring Boot 2.4, you need to use `spring-cloud-starter-bootstrap` dependency. https://github.com/PlaytikaOSS/testcontainers-spring-boot#how-to-use
* Disable composite indicator to avoid cast problems with …
> chore(dependencies): Bump orcaVersion

- kayenta-graphite/kayenta-graphite.gradle
- kayenta-integration-tests/kayenta-integration-tests.gradle
- kayenta-signalfx/kayenta-signalfx.gradle
Currently, version is pinned to io.rest-assured:rest-assured:4.3.2. Since it is a transitive dependency of spring boot, unpinning the same.
> chore(dependency): unpinning the version of io.rest-assured

- kayenta-sql/src/main/java/com/netflix/kayenta/sql/config/DataMigrationConfiguration.java
- kayenta-sql/src/main/java/com/netflix/kayenta/sql/config/DataMigrationProperties.java
- kayenta-sql/src/main/java/com/netflix/kayenta/sql/config/SqlConfiguration.java
- kayenta-sql/src/main/java/com/netflix/kayenta/sql/config/SqlProperties.java
- kayenta-sql/src/main/java/com/netflix/kayenta/sql/migration/StorageDataMigrator.java
- kayenta-sql/src/test/java/com/netflix/kayenta/sql/migration/StorageDataMigratorTest.java
- kayenta-sql/src/test/java/com/netflix/kayenta/sql/storage/SqlStorageServiceTest.java
**How to use?**
Data migration and SQL is disabled by default, use these properties (in kayenta-local.yml) to enable the data migration and MySQL or PostgreSQL data source.
```
kayenta:
sql:
enabled: true
data-migration:
enabled: true
sourceStorageServiceClassName: com.netflix.kayenta.s3.storage.S3StorageService
targetStorageServiceClassName: com.netflix.kayenta.sql.storage.SqlStorageService
sourceAccountName: monitoring
targetAccountName: monitoring
aws:
enabled: true
accounts:
- name: monitoring
bucket: ...
region: us-west-2
explicitCredentials:
accessKey: ...
secretKey: ...
sessionToken: ...
rootFolder: kayenta
roleName: default
supportedTypes:
- OBJECT_STORE
- CONFIGURATION_STORE
- METRICS_STORE
cloudwatch:
enabled: true
s3:
enabled: true
spring:
datasource:
driver-class-name: …
```
> feat: SPLAT-582: Add a storage data migrator.

- kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/security/SignalFxNamedAccountCredentials.java
- kayenta-signalfx/src/test/java/com/netflix/kayenta/signalfx/config/SignalFxConfigLoadTest.java
When we refactored the code to extend a base class... we missed a spot that had overloaded the type.  As a result of this no types were returned.  Drop downs for account lists currently don't work unless a type is shown for the given account.
> fix(signalfx): Fixed metric type missing due to duplicated field from parent class

- kayenta-graphite/kayenta-graphite.gradle
- kayenta-signalfx/kayenta-signalfx.gradle
While executing the build script with --warning-mode=fail received below error:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0
```
And the deprecated gradle features are:
```
> Configure project :kayenta-graphite
Adding a Configuration as a dependency is a confusing behavior which isn't recommended. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. If you're interested in inheriting the dependencies from the Configuration you are adding, you should use Configuration#extendsFrom instead. See https://docs.gradle.org/6.8.1/dsl/org.gradle.api.artifacts.Configuration.html#org.gradle.api.artifacts.Configuration:extendsFrom(org.gradle.api.artifacts.Configuration[]) for more details.
at …
```
> refactor(deprecation): remove deprecated gradle constructs/features from kayenta in order to upgrade gradle 7

- kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/MetricSetMixerServiceSpec.groovy
While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, encounter below error in test execution of kayenta-core module:
```
Error in @Unroll expression: controlMetricSet
at app//org.spockframework.runtime.extension.builtin.UnrollIterationNameProvider.evaluateExpression(UnrollIterationNameProvider.java:100)
at app//org.spockframework.runtime.extension.builtin.UnrollIterationNameProvider.nameFor(UnrollIterationNameProvider.java:55)
at app//org.spockframework.runtime.extension.builtin.UnrollIterationNameProvider.getName(UnrollIterationNameProvider.java:46)
at app//org.spockframework.runtime.extension.builtin.UnrollIterationNameProvider.getName(UnrollIterationNameProvider.java:30)
at app//org.spockframework.runtime.SafeIterationNameProvider.getName(SafeIterationNameProvider.java:33) …
```
> refactor(core/test): fix test placeholders to show unrolled iteration names during upgrade to groovy 3.x

- kayenta-core/src/main/java/com/netflix/kayenta/config/KayentaConfiguration.java
Currently if you define a new subtype locator in a plugin it is not possible to be loaded by the configurer because different classloaders are used. This refactoring will give the flexibility of customizing the `ObjectMapperSubtypeConfigurer` from the plugin system 
- ObjectMapperSubtypeConfigurer objectMapperSubtypeConfigurer is defined as a bean
- there's no need to autowire the mapper to configure but instead configure it when creating the kayentaObjectMapper bean
This will allow us to add more metrics providers (via the plugin framework)
> refactor: Refactor how the kayenta object mapper is being configured to allow overriding from kayenta plugins

- kayenta-prometheus/src/test/java/com/netflix/kayenta/prometheus/config/PrometheusHealthConfigurationTest.java
While upgrading spring boot 2.6.15 and spring cloud 2021.0.8, encounter below error in kayenta-prometheus module during test compilation:
```
> Task :kayenta-prometheus:compileTestJava FAILED
/kayenta/kayenta-prometheus/src/test/java/com/netflix/kayenta/prometheus/config/PrometheusHealthConfigurationTest.java:28: error: cannot find symbol
import org.springframework.boot.test.context.ConfigFileApplicationContextInitializer;
^
symbol:   class ConfigFileApplicationContextInitializer
location: package org.springframework.boot.test.context
1 error
```
The root cause is the removal of `ConfigFileApplicationContextInitializer` class which got deprecated since [spring boot 2.4.x](https://javadoc.io/doc/org.springframework.boot/spring-boot-test/2.4.4/deprecated-list.html) in favour of …
> refactor(prometheus/test): replace deprecated test application context initializer class during upgrade to spring boot 2.6.x

- kayenta-core/kayenta-core.gradle
The springfox swagger-ui and swagger2 dependencies are not part of the code, whereas io.swagger:swagger-annotations dependency is part of the code. Removing the swagger-ui and swagger2 dependency and introducing swagger-annotations dependency which is available as transitive dependency coming from kork-swagger via orca-bom in kayenta-core module.
The dependency insight before and after the cleanup given below:
Before cleanup: 
```
$ ./gradlew kayenta-web:dI --dependency swagger
> Task :kayenta-web:dependencyInsight
io.spinnaker.kork:kork-swagger:7.206.0
Variant compile:
| Attribute Name                 | Provided | Requested         |
|--------------------------------|----------|-------------------|
| org.gradle.status              | release  |                   |
| org.gradle.category …
```
> chore(dependency): unpinning and cleanup springfox dependencies

- kayenta-sql/kayenta-sql.gradle
mysql-connector-java and liquibase-core are transitive dependencies part of orca-bom.
Before:
```
$ ./gradlew kayenta-sql:dI --dependency mysql-connector-java --configuration runtimeClasspath
> Task :kayenta-sql:dependencyInsight
mysql:mysql-connector-java:8.0.33
Variant runtime:
| Attribute Name                 | Provided     | Requested    |
|--------------------------------|--------------|--------------|
| org.gradle.status              | release      |              |
| org.gradle.category            | library      | library      |
| org.gradle.libraryelements     | jar          | jar          |
| org.gradle.usage               | java-runtime | java-runtime |
| org.gradle.dependency.bundling |              | external     |
| org.gradle.jvm.environment     |              | standard-jvm …
```
> chore(dependency): unpin mysql-connector-java and liquibase-core

- Dockerfile
Kayenta build using Dockerfile is currently broken:
```
58.02 FAILURE: Build failed with an exception.
58.02 
58.02 * Where:
58.02 Build file '/tmp/workdir/build.gradle' line: 63
58.02 
58.02 * What went wrong:
58.02 A problem occurred evaluating root project 'kayenta'.
58.02 > Could not get unknown property 'javaToolchains' for task ':kayenta-atlas:test' of type org.gradle.api.tasks.testing.Test.
```
Gradle version was bumped to 7.6.1 in #967, but the base image for the build stage was not updated.
Changing it to `gradle:7.6.1-jdk17` fixes the build.
> chore(build): upgrade builder image to gradle:7.6.1-jdk17

- kayenta-google/kayenta-google.gradle
While upgrading spockframework 2.3-groovy-4.0, encountered below error during the build process of kayenta-google module:
```
/kayenta/kayenta-google/src/main/java/com/netflix/kayenta/google/security/GoogleClientFactory.java:24: error: package com.google.api.client.json.jackson2 does not exist
import com.google.api.client.json.jackson2.JacksonFactory;
```
Further, dependency insight does not show the dependency of `google-http-client-jackson2`:
```
> Task :kayenta-google:dependencyInsight
No dependencies matching given input were found in configuration ':kayenta-google:compileClasspath'
```
Whereas, before the spockframework upgrade this dependency transitively appears in insight:
```
> Task :kayenta-google:dependencyInsight
com.google.http-client:google-http-client-jackson2:1.41.7 …
```
> refactor(dependency): add explicit dependency of google-http-client-jackson2 while upgrading spockframework 2.3
